- name: Determine if first run
  stat: path=/etc/ansible/facts.d/last_run.fact
  register: last_run_fact

- name: Set first run fact if it is
  set_fact:
    first_run: true
  when: not last_run_fact.stat.exists

- name: Update APT package cache
  apt:
    update_cache: yes
  when: first_run is defined or apt_upgrade is defined

